#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

user=${SYNAPSE_USER:-sydent}
group=${SYNAPSE_GROUP:-sydent}
pidfile="/var/run/sydent/sydent.pid"
command="/usr/bin/sydent"
start_stop_daemon_args="--user ${user} --env SYDENT_CONF=/etc/sydent/sydent.conf --env SYDENT_DB_PATH=/var/lib/sydent/sydent.db --group ${group} --pidfile ${pidfile} -b -m"
